### ISSUE TITLE
Help dialog

### ISSUE THREAD

**Issue by im-n1** [im-n1/kosatka#1]
# Feature

## Description
The app needs a dialog (popup) that will show basic stuff like name, authors, version and then shortcuts.

The dialog will be binded to `?` key.

## TODO

* [ ] app has a dialog
* [ ] dialog has basic stuff (authors, year, version, description, ...)
* [ ] dialog has shortcuts described
